spring.application.name=discord-mcp
server.port=8085

spring.ai.mcp.server.name=discord-mcp-server
spring.ai.mcp.server.version=2.0.0-M4
spring.ai.mcp.server.protocol=STREAMABLE

spring.main.web-application-type=servlet
spring.main.banner-mode=off
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

logging.file.name=./target/logs/mcp-weather-stdio-server.log

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health
